### ISSUE TITLE
Classes BFWCtr\Controller introuvable

### ISSUE THREAD

**Issue by dremecker** [bulton-fr/bfw-controller#7]
Fatal error: Class 'BFWCtr\Controller' not found in /var/www/home/vendor/bulton-fr/bfw-controller/src/kernel_init.php on line 12

**Comment by bulton-fr** [comment]
Est-ce qu'un "composer update" a été fait ?
Si ce n'est pas le cas, ça explique cette erreur.

**Comment by bulton-fr** [comment]
Date d'il y a un an. Je ferme le ticket.
De mémoire de nos conversations par mails, ça avait été résolu.
